name: comment

on:
  issue_comment:
    types:
      - created
      - edited

permissions:
  id-token: write
  issues: read
  contents: write
  pull-requests: write
  statuses: write

jobs:
  prerequisites:
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/test')
    runs-on: ubuntu-22.04

    steps:
      - uses: xt0rted/pull-request-comment-branch@29fe0354c01b30fb3de76f193ab33abf8fe5ddb0 #1.2.0
        id: upstream_branch
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pending status
        run: |
          curl -L \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/${{ github.repository }}/statuses/${{ steps.upstream_branch.outputs.sha }} \
               -d '{"state":"pending","target_url":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}","description":"Start test","context":"${{ github.workflow }}"}'

    outputs:
      branch_name: ${{ steps.upstream_branch.outputs.head_ref }}
      commit_sha: ${{ steps.upstream_branch.outputs.head_sha }}

  test:
    needs: [prerequisites]
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright:v1.37.1-jammy

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          ref: ${{ needs.prerequisites.outputs.branch_name }}

      - name: Install jq tool
        run: |
          apt-get update
          apt-get -y install jq
  
      - name: Install japanese font
        run: apt-get install fonts-ipafont-gothic

      - name: Install dependencies
        run: pnpm install

      - if: ${{ !startsWith(github.event.comment.body, '/test-update-snapshots') }}
        name: Run test
        id: test
        run: npx playwright@1.37.1 test
        continue-on-error: true

      - if: startsWith(github.event.comment.body, '/test-update-snapshots')
        name: Run test with update snapshots
        id: test-update-snapshots
        run: npx playwright@1.37.1 test --update-snapshots
        continue-on-error: true

      - if: startsWith(github.event.comment.body, '/test-update-snapshots')
        name: Diff
        id: diff
        run: |
          git config --global --add safe.directory /__w/comment-action/comment-action
          git config --global user.name actions-user
          git config --global user.email action@github.com
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - if: steps.diff.outcome == 'failure'
        name: Commit diff
        run: |
          git add -A .
          git commit -m "Update snapshots"

      - if: steps.test.outcome == 'success' || steps.test-update-snapshots.outcome == 'success'
        name: Create comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2 # v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## ✅ Run test Success

      - if: steps.test.outcome == 'failure' || steps.test-update-snapshots.outcome == 'failure'
        name: Create comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2 # v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## ❌ Run test Failure

      - if: steps.test.outcome == 'success' || steps.test-update-snapshots.outcome == 'success'
        name: Notify successful status
        uses: hkusu/status-create-action@1040f888115fc10b2e0fa8efc8ef3b85a916af2e
        with:
          sha: ${{ needs.prerequisites.outputs.commit_sha }}
          state: success
          description: Successful

      - if: steps.test.outcome == 'failure' || steps.test-update-snapshots.outcome == 'failure'
        name: Notify failed status
        uses: hkusu/status-create-action@1040f888115fc10b2e0fa8efc8ef3b85a916af2e
        with:
          sha: ${{ needs.prerequisites.outputs.commit_sha }}
          state: failure
          description: Failed
